# Generated by Django 4.1.5 on 2023-01-18 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistanceBasePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('distance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeMultiplierFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_time', models.FloatField()),
                ('multiplier_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='DistanceAdditionalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aditinal_price', models.FloatField()),
                ('base_fare', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pricing.distancebaseprice')),
            ],
        ),
    ]
