# Generated by Django 4.1.5 on 2023-01-20 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_place_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPerson',
            fields=[
            ],
            options={
                'ordering': ['name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('pricing.place',),
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-name']},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['name']},
        ),
    ]
